In [8]:
import numpy as np

In [9]:
W_1 = [[1, 1, 1, 1],
       [1, 1, 2, 1],
       [1, 1, 1, 1]]
b_1 = np.ones((3, 1))

W_2 = [[1, 4, 1],
       [1, 1, 1]]
b_2 = np.ones((2, 1))

W_3 = [[1, 1],
       [3, 1],
       [1, 1]]
b_3 = np.ones((3, 1))

X_01 = np.ones((4, 1))

X_02 = [[1], [0], [0], [-1]]

Z_B = [[-1], [1], [-1]]

Z_A = [[1], [-1], [-1]]

In [10]:
def tanh(x):
    return (np.exp(0.5*x - 2) - np.exp(-0.5*x +2))/(np.exp(0.5*x - 2) + np.exp(-0.5*x +2))

def tanh_grad(x):
    return 0.5 * (1-tanh(x)**2)

def squared_error(z, x):
    return 0.5 * (z-x)**2

def squared_error_grad(z, x):
    return x-z

In [11]:
Z_11 = np.dot(W_1, X_01) + b_1
Z_12 = np.dot(W_1, X_02) + b_1

X_11 = tanh(Z_11)
X_12 = tanh(Z_12)

print("Z_11:\n", Z_11)
print("Z_21:\n", Z_12)
print("X_11:\n", X_11)
print("X_21:\n", X_12)

Z_11:
 [[5.]
 [6.]
 [5.]]
Z_21:
 [[1.]
 [1.]
 [1.]]
X_11:
 [[0.46211716]
 [0.76159416]
 [0.46211716]]
X_21:
 [[-0.90514825]
 [-0.90514825]
 [-0.90514825]]


In [12]:
Z_21 = np.dot(W_2, X_11) + b_2
Z_22 = np.dot(W_2, X_12) + b_2

X_21 = tanh(Z_21)
X_22 = tanh(Z_22)

print("Z_22:\n", Z_21)
print("Z_22:\n", Z_22)
print("X_21:\n", X_21)
print("X_22:\n", X_22)

Z_22:
 [[4.97061094]
 [2.68582847]]
Z_22:
 [[-4.43088952]
 [-1.71544476]]
X_21:
 [[ 0.45048251]
 [-0.57642073]]
X_22:
 [[-0.99956404]
 [-0.99343227]]


In [13]:
Z_31 = np.dot(W_3, X_21) + b_3
Z_32 = np.dot(W_3, X_22) + b_3

X_31 = tanh(Z_31)
X_32 = tanh(Z_32)

print("Z_31:\n", Z_31)
print("Z_32:\n", Z_32)
print("X_31:\n", X_31)
print("X_32:\n", X_32)

Z_31:
 [[0.87406178]
 [1.77502679]
 [0.87406178]]
Z_32:
 [[-0.99299631]
 [-2.99212439]
 [-0.99299631]]
X_31:
 [[-0.91590016]
 [-0.80493961]
 [-0.91590016]]
X_32:
 [[-0.98652085]
 [-0.9981635 ]
 [-0.98652085]]


In [14]:
delta_31 = squared_error_grad(Z_B, X_31)*tanh_grad(Z_31)
delta_32 = squared_error_grad(Z_A, X_32)*tanh_grad(Z_32)

W_31_grad = (squared_error_grad(Z_B, X_31)*tanh_grad(Z_31)).dot(X_21.T)
W_32_grad = (squared_error_grad(Z_A, X_32)*tanh_grad(Z_32)).dot(X_22.T)


print("delta_31:\n", delta_31)
print("delta_32:\n", delta_32)
print("W_31_grad:\n", W_31_grad)
print("W_32_grad:\n", W_32_grad)
print(squared_error_grad(Z_B, X_31))

delta_31:
 [[ 0.00677537]
 [-0.31773455]
 [ 0.00677537]]
delta_32:
 [[-2.65961421e-02]
 [ 3.36962051e-06]
 [ 1.80462886e-04]]
W_31_grad:
 [[ 0.00305219 -0.00390547]
 [-0.14313386  0.18314878]
 [ 0.00305219 -0.00390547]]
W_32_grad:
 [[ 2.65845472e-02  2.64214658e-02]
 [-3.36815150e-06 -3.34748975e-06]
 [-1.80384212e-04 -1.79277655e-04]]
[[ 0.08409984]
 [-1.80493961]
 [ 0.08409984]]


In [15]:
delta_21 = ((np.array(W_3).T).dot(delta_31))*tanh_grad(Z_21)
delta_22 = ((np.array(W_3).T).dot(delta_32))*tanh_grad(Z_22)

W_21_grad = (((np.array(W_3).T).dot(delta_31))*tanh_grad(Z_21)).dot(X_11.T)
W_22_grad = (((np.array(W_3).T).dot(delta_32))*tanh_grad(Z_22)).dot(X_12.T)


print("delta_21:\n", delta_21)
print("delta_22:\n", delta_22)
print("W_21_grad:\n", W_21_grad)
print("W_22_grad:\n", W_22_grad)

delta_21:
 [[-0.37448246]
 [-0.10155772]]
delta_22:
 [[-1.15092599e-05]
 [-1.72899298e-04]]
W_21_grad:
 [[-0.17305477 -0.28520366 -0.17305477]
 [-0.04693156 -0.07734576 -0.04693156]]
W_22_grad:
 [[1.04175865e-05 1.04175865e-05 1.04175865e-05]
 [1.56499498e-04 1.56499498e-04 1.56499498e-04]]


In [16]:
delta_11 = ((np.array(W_2).T).dot(delta_21))*tanh_grad(Z_11)
delta_12 = ((np.array(W_2).T).dot(delta_22))*tanh_grad(Z_12)

W_11_grad = (((np.array(W_2).T).dot(delta_21))*tanh_grad(Z_11)).dot(X_01.T)
W_12_grad = (((np.array(W_2).T).dot(delta_22))*tanh_grad(Z_12)).dot(np.array(X_02).T)

print("delta_11:\n", delta_11)
print("delta_12:\n", delta_12)
print("W_11_grad:\n", W_11_grad)
print("W_12_grad:\n", W_12_grad)

delta_11:
 [[-0.18719036]
 [-0.33587187]
 [-0.18719036]]
delta_12:
 [[-1.66619254e-05]
 [-1.97816249e-05]
 [-1.66619254e-05]]
W_11_grad:
 [[-0.18719036 -0.18719036 -0.18719036 -0.18719036]
 [-0.33587187 -0.33587187 -0.33587187 -0.33587187]
 [-0.18719036 -0.18719036 -0.18719036 -0.18719036]]
W_12_grad:
 [[-1.66619254e-05  0.00000000e+00  0.00000000e+00  1.66619254e-05]
 [-1.97816249e-05  0.00000000e+00  0.00000000e+00  1.97816249e-05]
 [-1.66619254e-05  0.00000000e+00  0.00000000e+00  1.66619254e-05]]


In [17]:
W_1_grad_total = W_11_grad + W_12_grad
W_2_grad_total = W_21_grad + W_22_grad
W_3_grad_total = W_31_grad + W_32_grad

In [18]:
lr = 0.1

W_1_grad_total = W_11_grad + W_12_grad

W_1 = W_1 - lr * W_1_grad_total

print("new W_1:\n", W_1)

new W_1:
 [[1.0187207  1.01871904 1.01871904 1.01871737]
 [1.03358917 1.03358719 2.03358719 1.03358521]
 [1.0187207  1.01871904 1.01871904 1.01871737]]


In [19]:
lr = 0.1

W_2_grad_total = W_21_grad + W_22_grad

W_2 = W_2 - lr * W_2_grad_total

print("new W_2:\n", W_2)

new W_2:
 [[1.01730444 4.02851932 1.01730444]
 [1.00467751 1.00771893 1.00467751]]


In [20]:
lr = 0.1

W_3_grad_total = W_31_grad + W_32_grad

W_3 = W_3 - lr * W_3_grad_total

print("new W_3:\n", W_3)

new W_3:
 [[0.99703633 0.9977484 ]
 [3.01431372 0.98168546]
 [0.99971282 1.00040847]]


In [21]:
lr = 0.1

b_1_grad_total = delta_11 + delta_12

b_1 = b_1 - lr * b_1_grad_total

print("new b_1:\n", b_1)

new b_1:
 [[1.0187207 ]
 [1.03358917]
 [1.0187207 ]]


In [22]:
lr = 0.1

b_2_grad_total = delta_21 + delta_22

b_2 = b_2 - lr * b_2_grad_total

print("new b_2:\n", b_2)

new b_2:
 [[1.0374494 ]
 [1.01017306]]


In [23]:
lr = 0.1

b_3_grad_total = delta_31 + delta_32

b_3 = b_3 - lr * b_3_grad_total

print("new b_3:\n", b_3)

new b_3:
 [[1.00198208]
 [1.03177312]
 [0.99930442]]
